### ISSUE TITLE
Use free CI and analysis systems

### ISSUE THREAD

**Issue by fawick** [jonas-p/go-shp#13]
- [x] Travis
- [x] Appveyor
- [x] Codecov 
- [x] Hound 
- [x] Goreportcard

I am going to tackle these over the next couple of days.

Edit: Added Goreportcard

**Comment by fawick** [comment]
Hi @jonas-p, it looks like I indeed still lack the admin role for this repo, so I cannot add the necessary webhooks for appveyor. In case you'd rather not to give admin permissions or would prefer not to include CI support, please let me know and I will roll back the changes accordingly.

**Comment by jonas-p** [comment]
Hi, I'm not sure it's possible to assign more granular permissions (according to https://help.github.com/articles/permission-levels-for-a-user-account-repository/), unless you know a way :).

Other than that, I think CI is a great idea and should definitely be part of the project. I see you've added files for travis/hound/appveyor so adding webhooks for them shouldn't be a problem for me.

**Comment by fawick** [comment]
Perfect, thanks! 

I also would love to add a badge for https://goreportcard.com/report/github.com/jonas-p/go-shp and start working on improving the results. For we would need a webhook that issues a  POST request to https://goreportcard.com/report/github.com/jonas-p/go-shp, I think.

**Comment by fawick** [comment]
@jonas-p any update on the webhooks?

**Comment by jonas-p** [comment]
@fawick  Webhooks for appveyor and goreportcard (pinging the url you mentioned) should be active now!

**Comment by fawick** [comment]
Thank you!

**Comment by fawick** [comment]
Sorry to bother you again but it looks like hound, codecov, and travis need some webhooks or activation from your end, as well. Otherwise PRs are not checked automatically.

**Comment by jonas-p** [comment]
I've reactivated Travis CI and Hound, I'll tackle codecov next. I assume existing PRs aren't run until they are updated in some way!
