### ISSUE TITLE
Append shapefiles without creating a copy in memory

### ISSUE THREAD

**Issue by gertcuykens** [jonas-p/go-shp#7]
Hi Jonas, as far as I understand, we can open a shapefile or create one but not append to one

```
shape, err := shp.Open("static-segments/segments.shp")
shape, err := shp.Create("new-static-segments/segments.shp", shp.MULTIPOINT)
```

Can we have a `shape, err := shp.Append("static-segments/segments.shp", shp.MULTIPOINT)` ?

Thanks

**Comment by fawick** [comment]
Good idea IMHO.

But why the shape type parameter for `shp.Append()`? Wouldn't the shape type be given by the existing file already? Or is your idea to have `Append` check and return an `error` if the type in the call to `Append` and the one in `segments.shp` do not match?

**Comment by gertcuykens** [comment]
yep you are 100% correct, sorry forgot about that :D 

So it would be
```
shape, err := shp.Append("static-segments/segments.shp")
```

**Comment by fawick** [comment]
@gertcuykens, @tdilo I invite you to test and review https://github.com/fawick/go-shp/tree/addAppend

**Comment by gertcuykens** [comment]
Any specific reason not to recycle err instead of er?
```
	er := &errReader{Reader: shp}
	w.bbox.MinX = readFloat64(er)
	w.bbox.MinY = readFloat64(er)
	w.bbox.MaxX = readFloat64(er)
	w.bbox.MaxY = readFloat64(er)
	if er.e != nil {
		return nil, fmt.Errorf("cannot read bounding box: %v", err)
	}
```

**Comment by fawick** [comment]
The reason is that readFloat64 does not return an error by itself. The errReader allow to check whether should could actually be read from in these four calls.to readFloat64.

**Comment by gertcuykens** [comment]
Ok i see maybe the last line should be 
```
return nil, fmt.Errorf("cannot read bounding box: %v", er.e)
```
then ?

**Comment by fawick** [comment]
Yes, you're absolutely right, thank you, good catch! Fixed.
